/*********************************************************************
 * FileName: HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * Processor: PIC18,PIC24E, PIC24F, PIC24H, dsPIC30F, dsPIC33F, dsPIC33E,PIC32
 * Compiler:  Microchip C18, C30, C32
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 *
 * Software License Agreement
 *
 * Copyright (C) 2012 Microchip Technology Inc.  All rights
 * reserved.
 *
 * Microchip licenses to you the right to use, modify, copy, and 
  * distribute: 
 * (i)  the Software when embedded on a Microchip microcontroller or 
 *      digital signal controller product ("Device") which is 
 *      integrated into Licensee's product; or 
 * (ii) ONLY the Software driver source files ENC28J60.c, ENC28J60.h,
 *		ENCX24J600.c and ENCX24J600.h ported to a non-Microchip device
 *		used in conjunction with a Microchip ethernet controller for
 *		the sole purpose of interfacing with the ethernet controller.
 *
 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * THE SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * MICROCHIP BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS
 * BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE 
 * THEREOF), ANY CLAIMS FOR INDEMNITY OR CONTRIBUTION, OR OTHER 
 * SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF CONTRACT, TORT
 * (INCLUDING NEGLIGENCE), BREACH OF WARRANTY, OR OTHERWISE.
 *
 *********************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_hellomsg(void);
void HTTPPrint_builddate(void);
void HTTPPrint_led(WORD);
void HTTPPrint_lcdtext(void);
void HTTPPrint_ledSelected(WORD,WORD);
void HTTPPrint_version(void);
void HTTPPrint_reboot(void);
void HTTPPrint_btn(WORD);
void HTTPPrint_pot(void);
void HTTPPrint_W_PASS(void);
void HTTPPrint_ELEV(void);
void HTTPPrint_W_ENB(void);
void HTTPPrint_status_fail(void);
void HTTPPrint_config_mac(void);
void HTTPPrint_config_hostname(void);
void HTTPPrint_config_dhcpchecked(void);
void HTTPPrint_config_ip(void);
void HTTPPrint_config_gw(void);
void HTTPPrint_config_subnet(void);
void HTTPPrint_config_dns1(void);
void HTTPPrint_config_dns2(void);
void HTTPPrint_rebootaddr(void);
void HTTPPrint_wifiSSID(void);
void HTTPPrint_wifiKey(void);
void HTTPPrint_wifiEnc(WORD);
void HTTPPrint_status_msg(void);
void HTTPPrint_nist_1(void);
void HTTPPrint_nist_2(void);
void HTTPPrint_WindDir(void);
void HTTPPrint_WindGust(void);
void HTTPPrint_WindSpeed(void);
void HTTPPrint_Temp_F(void);
void HTTPPrint_Dew_F(void);
void HTTPPrint_RelH(void);
void HTTPPrint_Baro_In(void);
void HTTPPrint_Sol_W(void);
void HTTPPrint_CALtg(void);
void HTTPPrint_CALhg(void);
void HTTPPrint_CALbo(void);
void HTTPPrint_CALho(void);
void HTTPPrint_CALwo(void);
void HTTPPrint_CALsg(void);
void HTTPPrint_W_IP(void);
void HTTPPrint_W_SID(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x00000000:
			HTTPIncFile((ROM BYTE*)"header.inc");
			break;
        case 0x00000001:
			HTTPPrint_hellomsg();
			break;
        case 0x00000002:
			HTTPIncFile((ROM BYTE*)"footer.inc");
			break;
        case 0x00000006:
			HTTPPrint_builddate();
			break;
        case 0x00000007:
			HTTPPrint_led(7);
			break;
        case 0x00000008:
			HTTPPrint_led(6);
			break;
        case 0x00000009:
			HTTPPrint_led(5);
			break;
        case 0x0000000a:
			HTTPPrint_led(4);
			break;
        case 0x0000000b:
			HTTPPrint_led(3);
			break;
        case 0x0000000c:
			HTTPPrint_led(2);
			break;
        case 0x0000000d:
			HTTPPrint_led(1);
			break;
        case 0x0000000e:
			HTTPPrint_led(0);
			break;
        case 0x0000000f:
			HTTPPrint_lcdtext();
			break;
        case 0x00000010:
			HTTPPrint_ledSelected(6,TRUE);
			break;
        case 0x00000011:
			HTTPPrint_ledSelected(6,FALSE);
			break;
        case 0x00000012:
			HTTPPrint_ledSelected(5,TRUE);
			break;
        case 0x00000013:
			HTTPPrint_ledSelected(5,FALSE);
			break;
        case 0x00000014:
			HTTPPrint_ledSelected(4,TRUE);
			break;
        case 0x00000015:
			HTTPPrint_ledSelected(4,FALSE);
			break;
        case 0x00000016:
			HTTPPrint_ledSelected(3,TRUE);
			break;
        case 0x00000017:
			HTTPPrint_ledSelected(3,FALSE);
			break;
        case 0x00000018:
			HTTPPrint_ledSelected(2,TRUE);
			break;
        case 0x00000019:
			HTTPPrint_ledSelected(2,FALSE);
			break;
        case 0x0000001a:
			HTTPPrint_ledSelected(1,TRUE);
			break;
        case 0x0000001b:
			HTTPPrint_ledSelected(1,FALSE);
			break;
        case 0x0000001c:
			HTTPPrint_version();
			break;
        case 0x0000001d:
			HTTPPrint_reboot();
			break;
        case 0x0000001e:
			HTTPPrint_btn(0);
			break;
        case 0x0000001f:
			HTTPPrint_btn(1);
			break;
        case 0x00000020:
			HTTPPrint_btn(2);
			break;
        case 0x00000021:
			HTTPPrint_btn(3);
			break;
        case 0x00000022:
			HTTPPrint_pot();
			break;
        case 0x00000023:
			HTTPPrint_W_PASS();
			break;
        case 0x00000024:
			HTTPPrint_ELEV();
			break;
        case 0x00000026:
			HTTPPrint_W_ENB();
			break;
        case 0x00000027:
			HTTPPrint_status_fail();
			break;
        case 0x00000028:
			HTTPPrint_config_mac();
			break;
        case 0x00000029:
			HTTPPrint_config_hostname();
			break;
        case 0x0000002a:
			HTTPPrint_config_dhcpchecked();
			break;
        case 0x0000002b:
			HTTPPrint_config_ip();
			break;
        case 0x0000002c:
			HTTPPrint_config_gw();
			break;
        case 0x0000002d:
			HTTPPrint_config_subnet();
			break;
        case 0x0000002e:
			HTTPPrint_config_dns1();
			break;
        case 0x0000002f:
			HTTPPrint_config_dns2();
			break;
        case 0x00000030:
			HTTPPrint_rebootaddr();
			break;
        case 0x00000033:
			HTTPPrint_wifiSSID();
			break;
        case 0x00000035:
			HTTPPrint_wifiKey();
			break;
        case 0x00000036:
			HTTPPrint_wifiEnc(0);
			break;
        case 0x00000037:
			HTTPPrint_wifiEnc(1);
			break;
        case 0x00000038:
			HTTPPrint_wifiEnc(2);
			break;
        case 0x00000039:
			HTTPPrint_wifiEnc(3);
			break;
        case 0x0000003a:
			HTTPPrint_wifiEnc(4);
			break;
        case 0x0000003b:
			HTTPPrint_wifiEnc(5);
			break;
        case 0x0000003c:
			HTTPPrint_wifiEnc(6);
			break;
        case 0x0000003d:
			HTTPPrint_wifiEnc(7);
			break;
        case 0x0000003e:
			HTTPPrint_wifiEnc(8);
			break;
        case 0x0000003f:
			HTTPPrint_status_msg();
			break;
        case 0x00000042:
			HTTPPrint_nist_1();
			break;
        case 0x00000043:
			HTTPPrint_nist_2();
			break;
        case 0x00000044:
			HTTPPrint_WindDir();
			break;
        case 0x00000045:
			HTTPPrint_WindGust();
			break;
        case 0x00000046:
			HTTPPrint_WindSpeed();
			break;
        case 0x00000047:
			HTTPPrint_Temp_F();
			break;
        case 0x00000048:
			HTTPPrint_Dew_F();
			break;
        case 0x00000049:
			HTTPPrint_RelH();
			break;
        case 0x0000004a:
			HTTPPrint_Baro_In();
			break;
        case 0x0000004b:
			HTTPPrint_Sol_W();
			break;
        case 0x0000004c:
			HTTPPrint_CALtg();
			break;
        case 0x0000004d:
			HTTPPrint_CALhg();
			break;
        case 0x0000004f:
			HTTPPrint_CALbo();
			break;
        case 0x00000050:
			HTTPPrint_CALho();
			break;
        case 0x00000051:
			HTTPPrint_CALwo();
			break;
        case 0x00000052:
			HTTPPrint_CALsg();
			break;
        case 0x00000053:
			HTTPPrint_W_IP();
			break;
        case 0x00000054:
			HTTPPrint_W_SID();
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
