<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Weather Underground Rapid Fire Station</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/ajax.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div id="title"><div class="right">Wunderground </div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">Overview</a>
<a href="/compas.htm">Compass </a>
<a href="/wunder.htm">Weather Underground</a>
<!--
<a href="/email">Send E-mail</a>
-->
<a href="/dyndns">Dynamic DNS</a>
<a href="/protect/config.htm">Network Configuration</a>
<a href="/protect/wuncfg.htm">WunderSetup </a>
<a href="/protect/reboot.htm">Reboot </a>
</div>